mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.tao.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 2
      max-total: 5
      max-wait-millis: 200

server:
  port: 8001

debug: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #将客户端注册进eureka服务列表内
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: tao-microservicecloud
  company.name: www.tao.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
